# Generated by Django 3.2 on 2021-04-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Номер телефона'),
        ),
    ]
