# Generated by Django 3.2 on 2021-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='item_images', verbose_name='Картинка')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес в граммах')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена в рублях')),
            ],
            options={
                'verbose_name': 'Комплект подарков',
                'verbose_name_plural': 'Комплекты подарков',
            },
        ),
    ]
